const adress = [
  { number: 5202, street: 'Heming Ave' },
  { number: 7419, street: 'Gresham St' },
  { number: 7304, street: 'Elgar St' },
  { number: 5212, street: 'Ferndale St' },
  { number: 7506, street: 'Hogarth St' },
  { number: 7516, street: 'Hogarth St' },
  { number: 5301, street: 'Heming Ave' },
  { number: 1525, street: 'Q St NW' },
  { number: 5209, street: 'Kipling St' },
  { number: 1212, street: '30th St NW' },
  { number: 7608, street: 'Jervis St' },
  { number: 1225, street: '13th St NW APT 1020' },
  { number: 7225, street: 'Braddock Rd' },
  { number: 1718, street: 'P st NW # T6' },
  { number: 7220, street: 'Hansford Ct' },
  { number: 7113, street: 'Granberry Way' },
  { number: 7127, street: 'Woodland Dr' },
  { number: 7410, street: 'Gresham St' },
  { number: 7014, street: 'Woodland Dr' },
  { number: 7006, street: 'Leesville Blvd' },
  { number: 7014, street: 'Appomattox Ct' },
  { number: 5539, street: 'Belfast Pl' },
  { number: 7104, street: 'Granberry Way' },
  { number: 5216, street: 'Garner St' },
  { number: 7101, street: 'Catlett St' },
  { number: 7108, street: 'Leesville Blvd' },
  { number: 5222, street: 'Garner St' },
  { number: 7211, street: 'Leesville Blvd' },
  { number: 7209, street: 'Cattlett St' },
  { number: 7202, street: 'Cattlett St' },
];

export default adress;
